### ISSUE TITLE
Variables scoping

### ISSUE THREAD

**Issue by kdo** [timwright12/barebones-a11y-skipper#8]
Wondering if maybe https://github.com/timwright12/barebones-a11y-skipper/blob/master/src/components/config/variables.css should be scoped to the skipper?

```
--c-black: #333;
--c-white: #eee;
```

was conflicting with my theme's variables 😅

**Comment by timwright12** [comment]
This is merged https://github.com/timwright12/barebones-a11y-skipper/blob/master/src/components/config/variables.css
